# -*- coding: utf-8 -*-
"""Copy of Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWTo7muQQm0hu76_3gzhaFE0Ezvq4HRf
"""

import pandas as pd

df = pd.read_csv("/content/tested.csv")
print(df.head())

import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv("/content/tested.csv")

# Handle missing values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Remove duplicates
df = df.drop_duplicates()

# Feature Engineering - Extract title from name
df['Title'] = df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)

# Create Age Groups
df['AgeGroup'] = pd.cut(
    df['Age'],
    bins=[0, 12, 19, 35, 60, 100],
    labels=['Child', 'Teen', 'Young Adult', 'Adult', 'Senior']
)

# Create Family Size
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

# Convert categorical features to numerical
df = pd.get_dummies(df, columns=['Sex', 'Embarked', 'Title'], drop_first=True)

# Scale numerical features
scaler = StandardScaler()
df[['Age', 'Fare', 'FamilySize']] = scaler.fit_transform(
    df[['Age', 'Fare', 'FamilySize']]
)

# Display results
print("First 5 rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())